main: io.github.evercraftmc.rp_utils.Main

name: RoleplayUtils
version: ${plugin_version}
description: A collection of useful commands and more for roleplay servers
author: Kale Ko
website: https://github.com/EverCraft/Roleplay-Utils

api-version: "1.19"
load: POSTWORLD
