main: io.github.evercraftmc.roleplayutils.Main

name: RoleplayUtils
version: ${plugin_version}
description: A collection of useful commands and more for roleplay servers
author: Kale Ko
website: https://github.com/EverCraft/RoleplayUtils

api-version: "1.20"
load: POSTWORLD
